require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trader_stocks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TraderStock. As you add validations to TraderStock, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TraderStock.create! valid_attributes
      get trader_stocks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      trader_stock = TraderStock.create! valid_attributes
      get trader_stock_url(trader_stock)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_trader_stock_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      trader_stock = TraderStock.create! valid_attributes
      get edit_trader_stock_url(trader_stock)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TraderStock" do
        expect {
          post trader_stocks_url, params: { trader_stock: valid_attributes }
        }.to change(TraderStock, :count).by(1)
      end

      it "redirects to the created trader_stock" do
        post trader_stocks_url, params: { trader_stock: valid_attributes }
        expect(response).to redirect_to(trader_stock_url(TraderStock.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TraderStock" do
        expect {
          post trader_stocks_url, params: { trader_stock: invalid_attributes }
        }.to change(TraderStock, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post trader_stocks_url, params: { trader_stock: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested trader_stock" do
        trader_stock = TraderStock.create! valid_attributes
        patch trader_stock_url(trader_stock), params: { trader_stock: new_attributes }
        trader_stock.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the trader_stock" do
        trader_stock = TraderStock.create! valid_attributes
        patch trader_stock_url(trader_stock), params: { trader_stock: new_attributes }
        trader_stock.reload
        expect(response).to redirect_to(trader_stock_url(trader_stock))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        trader_stock = TraderStock.create! valid_attributes
        patch trader_stock_url(trader_stock), params: { trader_stock: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested trader_stock" do
      trader_stock = TraderStock.create! valid_attributes
      expect {
        delete trader_stock_url(trader_stock)
      }.to change(TraderStock, :count).by(-1)
    end

    it "redirects to the trader_stocks list" do
      trader_stock = TraderStock.create! valid_attributes
      delete trader_stock_url(trader_stock)
      expect(response).to redirect_to(trader_stocks_url)
    end
  end
end
